const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('WWE2K26Desktop', {
  getAppInfo: () => ipcRenderer.invoke('desktop:get-app-info'),
  chooseProjectFolder: () => ipcRenderer.invoke('desktop:choose-project-folder'),
  openDefaultProjectsFolder: () => ipcRenderer.invoke('desktop:open-default-projects-folder'),
  openDefaultExportsFolder: () => ipcRenderer.invoke('desktop:open-default-exports-folder'),
  saveTextFile: (payload) => ipcRenderer.invoke('desktop:save-text-file', payload),
  createProjectFolder: (payload) => ipcRenderer.invoke('desktop:create-project-folder', payload),
  saveProjectJson: (payload) => ipcRenderer.invoke('desktop:save-project-json', payload),
  openProjectJson: () => ipcRenderer.invoke('desktop:open-project-json'),
  getToolConfig: () => ipcRenderer.invoke('desktop:get-tool-config'),
  chooseToolPath: (toolId) => ipcRenderer.invoke('desktop:choose-tool-path', toolId),
  clearToolPath: (toolId) => ipcRenderer.invoke('desktop:clear-tool-path', toolId),
  openConfiguredTool: (toolId) => ipcRenderer.invoke('desktop:open-configured-tool', toolId),
  checkCakeHook: () => ipcRenderer.invoke('desktop:check-cakehook'),
  getDdsConverterStatus: () => ipcRenderer.invoke('desktop:dds-converter-status'),
  chooseDdsConverterInputs: (mode) => ipcRenderer.invoke('desktop:dds-converter-choose-inputs', mode),
  chooseDdsConverterFolder: (mode) => ipcRenderer.invoke('desktop:dds-converter-choose-folder', mode),
  chooseDdsConverterOutput: () => ipcRenderer.invoke('desktop:dds-converter-choose-output'),
  chooseDdsReferenceFolder: () => ipcRenderer.invoke('desktop:dds-converter-choose-reference-folder'),
  runDdsConversion: (payload) => ipcRenderer.invoke('desktop:dds-converter-run', payload),
  openDdsConverterOutput: () => ipcRenderer.invoke('desktop:dds-converter-open-output')
  ,openReferenceModelsFolder: () => ipcRenderer.invoke('desktop:open-reference-models-folder')
  ,getCakExplorerStatus: () => ipcRenderer.invoke('desktop:cak-explorer-status')
  ,chooseCakArchive: () => ipcRenderer.invoke('desktop:cak-explorer-choose-archive')
  ,openCakArchive: (archivePath) => ipcRenderer.invoke('desktop:cak-explorer-open', archivePath)
  ,openAllCakArchives: () => ipcRenderer.invoke('desktop:cak-explorer-open-all')
  ,searchCakArchive: (options) => ipcRenderer.invoke('desktop:cak-explorer-search', options)
  ,chooseCakOutput: () => ipcRenderer.invoke('desktop:cak-explorer-choose-output')
   ,extractCakEntries: (payload) => ipcRenderer.invoke('desktop:cak-explorer-extract', payload)
  ,onCakExtractionProgress: (callback) => { const listener = (_event, payload) => callback(payload); ipcRenderer.on('desktop:cak-extraction-progress', listener); return () => ipcRenderer.removeListener('desktop:cak-extraction-progress', listener); }
  ,openCakOutput: () => ipcRenderer.invoke('desktop:cak-explorer-open-output')
  ,chooseRepackSource: () => ipcRenderer.invoke('desktop:repackager-choose-source')
  ,buildRepackPackage: (sourceRoot) => ipcRenderer.invoke('desktop:repackager-build', sourceRoot)
  ,verifyRepackPackage: () => ipcRenderer.invoke('desktop:repackager-verify')
  ,openRepackOutput: () => ipcRenderer.invoke('desktop:repackager-open-output')
  ,createModSuiteWorkspace: () => ipcRenderer.invoke('desktop:mod-suite-create-workspace')
  ,chooseAndAuditModFolder: () => ipcRenderer.invoke('desktop:mod-suite-choose-audit-folder')
  ,openModSuiteFolder: (folderPath) => ipcRenderer.invoke('desktop:mod-suite-open-folder', folderPath)
  ,getPac19Status: () => ipcRenderer.invoke('desktop:pac19-status')
  ,choosePac19GameFolder: () => ipcRenderer.invoke('desktop:pac19-choose-game-folder')
  ,choosePac19Archive: () => ipcRenderer.invoke('desktop:pac19-choose-archive')
  ,openPac19Archive: (archivePath) => ipcRenderer.invoke('desktop:pac19-open', archivePath)
  ,choosePac19Output: () => ipcRenderer.invoke('desktop:pac19-choose-output')
  ,extractPac19Entries: (payload) => ipcRenderer.invoke('desktop:pac19-extract', payload)
  ,openPac19Output: () => ipcRenderer.invoke('desktop:pac19-open-output')
  ,choosePac19Replacement: () => ipcRenderer.invoke('desktop:pac19-choose-replacement')
  ,replacePac19Entry: (payload) => ipcRenderer.invoke('desktop:pac19-replace', payload)
  ,analyzePac19Motion: () => ipcRenderer.invoke('desktop:pac19-analyze-motion')
  ,getCak20Status: () => ipcRenderer.invoke('desktop:cak20-status')
  ,chooseCak20GameFolder: () => ipcRenderer.invoke('desktop:cak20-choose-game-folder')
  ,listCak20Files: (options) => ipcRenderer.invoke('desktop:cak20-list-files', options)
  ,chooseCak20Output: () => ipcRenderer.invoke('desktop:cak20-choose-output')
  ,extractCak20Entries: (payload) => ipcRenderer.invoke('desktop:cak20-extract', payload)
  ,openCak20Output: () => ipcRenderer.invoke('desktop:cak20-open-output')
  ,getWorkshopCapabilities: () => ipcRenderer.invoke('desktop:workshop-capabilities')
  ,chooseWwe2K26Install: () => ipcRenderer.invoke('desktop:workshop-choose-wwe2k26')
  ,chooseSecureDataCtrlLink: () => ipcRenderer.invoke('desktop:workshop-choose-secure-loader')
  ,chooseSecureDataCtrlLinkZip: () => ipcRenderer.invoke('desktop:workshop-choose-secure-loader-zip')
  ,downloadSecureDataCtrlLink: () => ipcRenderer.invoke('desktop:workshop-download-secure-loader', { confirm: true })
  ,installSecureDataCtrlLink: () => ipcRenderer.invoke('desktop:workshop-install-secure-loader', { confirm: true })
  ,rollbackSecureDataCtrlLink: (operationId) => ipcRenderer.invoke('desktop:workshop-rollback-secure-loader', { confirm: true, operationId })
  ,getWorkshopJournal: () => ipcRenderer.invoke('desktop:workshop-journal')
  ,getWorkshopRedactedReport: () => ipcRenderer.invoke('desktop:workshop-redacted-report')
  ,getSecureDataCtrlLinkDiagnostics: () => ipcRenderer.invoke('desktop:workshop-loader-diagnostics')
  ,getCakCollisionReport: () => ipcRenderer.invoke('desktop:workshop-cak-collisions')
  ,getModManifest: () => ipcRenderer.invoke('desktop:workshop-mod-manifest')
  ,saveModManifest: (request) => ipcRenderer.invoke('desktop:workshop-save-mod-manifest', request)
});
